import CryptoKit
import XCTest
@testable import SharedAppleRemoteCore

/// Golden-fixture replay: every wire fixture generated by
/// `dsh-link-contracts` decodes into the generated model and round-trips
/// losslessly — the Apple side of the cross-language contract drift CI.
final class FixtureDecodingTests: XCTestCase {
    private var fixturesDirectory: URL {
        URL(fileURLWithPath: #filePath, isDirectory: false)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures", isDirectory: true)
    }

    private func fixture(_ id: String) throws -> Data {
        try Data(contentsOf: fixturesDirectory.appendingPathComponent("\(id).json"))
    }

    func testPairingPayloadDecodesAndRoundTrips() throws {
        let data = try fixture("pairing-payload")
        let payload = try JSONDecoder().decode(LinkPairingPayload.self, from: data)
        XCTAssertEqual(payload.v, 1)
        XCTAssertEqual(payload.kind, "dsh-link-pairing")
        XCTAssertEqual(payload.endpoint, "https://192.168.1.4:4931")
        XCTAssertEqual(payload.spkiFingerprint.count, 64)
        let reencoded = try JSONEncoder().encode(payload)
        XCTAssertEqual(try JSONSerialization.jsonObject(with: reencoded) as? [String: Any],
                       try JSONSerialization.jsonObject(with: data) as? [String: Any])
    }

    func testPairResponseDecodes() throws {
        let value = try JSONDecoder().decode(LinkPairResponse.self, from: fixture("pair-response"))
        XCTAssertEqual(value.role, .controller)
        XCTAssertEqual(value.linkProtocolVersion, 1)
        XCTAssertFalse(value.deviceId.isEmpty)
    }

    func testHostDescriptionCarriesCapabilities() throws {
        let description = try JSONDecoder().decode(LinkHostDescription.self, from: fixture("host-description"))
        XCTAssertEqual(description.runtimeClass, "full")
        XCTAssertTrue(description.capabilities.session.prompt)
        XCTAssertTrue(description.capabilities.workspace.follow)
        XCTAssertFalse(description.capabilities.interaction.approval)
        XCTAssertFalse(description.allowRemoteApproval)
    }

    func testCarrierStatusDecodes() throws {
        let status = try JSONDecoder().decode(LinkCarrierStatus.self, from: fixture("carrier-status"))
        XCTAssertTrue(status.listening)
        XCTAssertEqual(status.endpoint, "https://192.168.1.4:4931")
        XCTAssertNil(status.bindError)
    }

    func testDeviceRecordDecodes() throws {
        let record = try JSONDecoder().decode(LinkDeviceRecord.self, from: fixture("device-record"))
        XCTAssertEqual(record.role, .controller)
        XCTAssertNil(record.revokedAt)
        XCTAssertNotNil(record.lastSeenAt)
    }

    func testAdminStatusDecodes() throws {
        let status = try JSONDecoder().decode(LinkAdminStatus.self, from: fixture("admin-status"))
        XCTAssertFalse(status.listening)
        XCTAssertEqual(status.bindError, "EADDRINUSE listen")
        XCTAssertEqual(status.deviceCount, 2)
    }

    /// Every session-event and chunk-row fixture decodes into its contract
    /// model and re-encodes to the same JSON — the cross-language drift
    /// guarantee for the event vocabulary.
    func testSessionEventPayloadsDecodeAndRoundTrip() throws {
        try roundTrip("event-turn-start", as: LinkTurnStartData.self)
        try roundTrip("event-turn-end", as: LinkTurnEndData.self)
        try roundTrip("event-step-start", as: LinkStepSpanData.self)
        try roundTrip("event-user-message", as: LinkUserMessageData.self)
        try roundTrip("event-assistant-chunk", as: LinkAssistantChunkData.self)
        try roundTrip("event-assistant-message", as: LinkAssistantMessageData.self)
        try roundTrip("event-tool-call", as: LinkToolCallData.self)
        try roundTrip("event-tool-result", as: LinkToolResultData.self)
        try roundTrip("event-plan-mode", as: LinkPlanModeData.self)
        try roundTrip("event-todo-write", as: LinkTodoWriteData.self)
        try roundTrip("event-goal-change", as: LinkGoalChangeData.self)
        try roundTrip("chunkrow-text-chunks", as: LinkTextChunksData.self)
        try roundTrip("chunkrow-tool-call-chunks", as: LinkToolCallChunksData.self)
    }

    private func roundTrip<T: Codable>(_ id: String, as type: T.Type) throws {
        let data = try fixture(id)
        let value = try JSONDecoder().decode(T.self, from: data)
        let reencoded = try JSONEncoder().encode(value)
        XCTAssertEqual(
            try JSONSerialization.jsonObject(with: reencoded) as? [String: Any],
            try JSONSerialization.jsonObject(with: data) as? [String: Any],
            "fixture \(id) must round-trip losslessly"
        )
    }

    func testEventVocabularyEnumsCarryTheWireTags() {
        XCTAssertEqual(LinkSessionEventKind.turnStart.rawValue, "turn/start")
        XCTAssertEqual(LinkSessionEventKind.sessionEndSeed.rawValue, "session/end-seed")
        XCTAssertEqual(LinkChunkRowKind.textChunks.rawValue, "chunkrow/text-chunks")
        XCTAssertEqual(LinkTurnEndReasonKind.maxTokens.rawValue, "max-tokens")
        XCTAssertEqual(LinkTodoStatus.inProgress.rawValue, "in_progress")
    }

    func testGoalChangeDecodesSnapshotFields() throws {
        let payload = try JSONDecoder().decode(LinkGoalChangeData.self, from: fixture("event-goal-change"))
        XCTAssertEqual(payload.operation, .create)
        XCTAssertEqual(payload.goal?.phase, .active)
        XCTAssertEqual(payload.goal?.objective, "发布 0.2 伴侣版")
        XCTAssertEqual(payload.goal?.revision, 1)
        XCTAssertNil(payload.clearedAt)
    }

    func testTodoWriteDecodesStatuses() throws {
        let payload = try JSONDecoder().decode(LinkTodoWriteData.self, from: fixture("event-todo-write"))
        XCTAssertEqual(payload.todos.map(\.content), ["编译伴侣应用", "跑契约回放测试"])
        XCTAssertEqual(payload.todos.map(\.status), [.inProgress, .pending])
    }

    func testAttachmentVocabularyDecodesAndRoundTrips() throws {
        let ref = try JSONDecoder().decode(LinkImageAttachmentRef.self, from: fixture("image-attachment-ref"))
        XCTAssertEqual(ref.attachmentId, "att-8f14e45fceea167a5a36dedd4bea2543")
        XCTAssertEqual(ref.mediaType, .imagePng)
        XCTAssertEqual(ref.bytes, 52_444)
        XCTAssertEqual(ref.originalDimensions?.width, 1600)

        let read = try JSONDecoder().decode(LinkAttachmentReadValue.self, from: fixture("attachment-read"))
        XCTAssertEqual(read.attachment.attachmentId, ref.attachmentId)
        XCTAssertEqual(read.data, "iVBORw0KGgo=")

        let part = try JSONDecoder().decode(LinkPromptImagePart.self, from: fixture("prompt-image-part"))
        XCTAssertEqual(part.type, "image")
        XCTAssertEqual(part.mediaType, .imagePng)
        XCTAssertEqual(part.name, "screenshot.png")

        for (id, value) in [("image-attachment-ref", ref), ("attachment-read", read), ("prompt-image-part", part)] {
            let reencoded = try JSONEncoder().encode(value)
            XCTAssertEqual(
                try JSONSerialization.jsonObject(with: reencoded) as? [String: Any],
                try JSONSerialization.jsonObject(with: fixture(id)) as? [String: Any]
            )
        }
    }

    func testToolResultDecodesNestedContent() throws {
        let payload = try JSONDecoder().decode(LinkToolResultData.self, from: fixture("event-tool-result"))
        let block = try XCTUnwrap(payload.message.content.first)
        XCTAssertEqual(block.type, "tool-result")
        XCTAssertEqual(block.toolCallId, "call-1")
        XCTAssertEqual(block.content?.first?.text, "已写入 42 行。")
        XCTAssertNil(payload.error)
    }
}

/// Signing and framing vocabulary checks that need no network.
final class LinkSigningTests: XCTestCase {
    func testSigningInputIsCanonical() {
        XCTAssertEqual(
            LinkSigning.signingInput(timestamp: "1000", method: "POST", path: "/api/x", bodySha256Hex: "ab"),
            "1000\nPOST\n/api/x\nab"
        )
    }

    func testEd25519SpkiDerIs44Bytes() {
        let key = Curve25519.Signing.PrivateKey()
        let der = LinkSigning.ed25519SpkiDer(publicKeyRaw: key.publicKey.rawRepresentation)
        XCTAssertEqual(der.count, 44)
        XCTAssertEqual(LinkSigning.spkiFingerprint(spkiDer: der).count, 64)
    }

    func testSignAndVerifyRoundTrip() throws {
        let key = Curve25519.Signing.PrivateKey()
        let signature = try LinkSigning.sign(input: "input", privateKeyRaw: key.rawRepresentation)
        let signatureData = Data(base64Encoded: signature)!
        XCTAssertTrue(key.publicKey.isValidSignature(signatureData, for: Data("input".utf8)))
    }

    func testCredentialsStoreRoundTrip() {
        let store = MemoryLinkCredentialsStore()
        XCTAssertNil(store.load())
        let credentials = LinkCredentials(
            deviceId: "device", hostId: "host", hostName: "Studio Desk", role: "controller",
            signingKeyBase64: Data(repeating: 1, count: 32).base64EncodedString()
        )
        store.save(credentials)
        XCTAssertEqual(store.load(), credentials)
        store.clear()
        XCTAssertNil(store.load())
    }
}
