import CryptoKit
import XCTest
@testable import SharedAppleRemoteCore

/// Golden-fixture replay: every wire fixture generated by
/// `dsh-link-contracts` decodes into the generated model and round-trips
/// losslessly — the Apple side of the cross-language contract drift CI.
final class FixtureDecodingTests: XCTestCase {
    private var fixturesDirectory: URL {
        URL(fileURLWithPath: #filePath, isDirectory: false)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures", isDirectory: true)
    }

    private func fixture(_ id: String) throws Data {
        try Data(contentsOf: fixturesDirectory.appendingPathComponent("\(id).json"))
    }

    func testPairingPayloadDecodesAndRoundTrips() throws {
        let data = try fixture("pairing-payload")
        let payload = try JSONDecoder().decode(LinkPairingPayload.self, from: data)
        XCTAssertEqual(payload.v, 1)
        XCTAssertEqual(payload.kind, "dsh-link-pairing")
        XCTAssertEqual(payload.endpoint, "https://192.168.1.4:4931")
        XCTAssertEqual(payload.spkiFingerprint.count, 64)
        let reencoded = try JSONEncoder().encode(payload)
        XCTAssertEqual(try JSONSerialization.jsonObject(with: reencoded) as? [String: Any],
                       try JSONSerialization.jsonObject(with: data) as? [String: Any])
    }

    func testPairResponseDecodes() throws {
        let value = try JSONDecoder().decode(LinkPairResponse.self, from: fixture("pair-response"))
        XCTAssertEqual(value.role, .controller)
        XCTAssertEqual(value.linkProtocolVersion, 1)
        XCTAssertFalse(value.deviceId.isEmpty)
    }

    func testHostDescriptionCarriesCapabilities() throws {
        let description = try JSONDecoder().decode(LinkHostDescription.self, from: fixture("host-description"))
        XCTAssertEqual(description.runtimeClass, "full")
        XCTAssertTrue(description.capabilities.session.prompt)
        XCTAssertTrue(description.capabilities.workspace.follow)
        XCTAssertFalse(description.capabilities.interaction.approval)
        XCTAssertFalse(description.allowRemoteApproval)
    }

    func testCarrierStatusDecodes() throws {
        let status = try JSONDecoder().decode(LinkCarrierStatus.self, from: fixture("carrier-status"))
        XCTAssertTrue(status.listening)
        XCTAssertEqual(status.endpoint, "https://192.168.1.4:4931")
        XCTAssertNil(status.bindError)
    }

    func testDeviceRecordDecodes() throws {
        let record = try JSONDecoder().decode(LinkDeviceRecord.self, from: fixture("device-record"))
        XCTAssertEqual(record.role, .controller)
        XCTAssertNil(record.revokedAt)
        XCTAssertNotNil(record.lastSeenAt)
    }

    func testAdminStatusDecodes() throws {
        let status = try JSONDecoder().decode(LinkAdminStatus.self, from: fixture("admin-status"))
        XCTAssertFalse(status.listening)
        XCTAssertEqual(status.bindError, "EADDRINUSE listen")
        XCTAssertEqual(status.deviceCount, 2)
    }
}

/// Signing and framing vocabulary checks that need no network.
final class LinkSigningTests: XCTestCase {
    func testSigningInputIsCanonical() {
        XCTAssertEqual(
            LinkSigning.signingInput(timestamp: "1000", method: "POST", path: "/api/x", bodySha256Hex: "ab"),
            "1000\nPOST\n/api/x\nab"
        )
    }

    func testEd25519SpkiDerIs44Bytes() {
        let key = Curve25519.Signing.PrivateKey()
        let der = LinkSigning.ed25519SpkiDer(publicKeyRaw: key.publicKey.rawRepresentation)
        XCTAssertEqual(der.count, 44)
        XCTAssertEqual(LinkSigning.spkiFingerprint(spkiDer: der).count, 64)
    }

    func testSignAndVerifyRoundTrip() throws {
        let key = Curve25519.Signing.PrivateKey()
        let signature = try LinkSigning.sign(input: "input", privateKeyRaw: key.rawRepresentation)
        let signatureData = Data(base64Encoded: signature)!
        XCTAssertTrue(key.publicKey.isValidSignature(signatureData, for: Data("input".utf8)))
    }

    func testCredentialsStoreRoundTrip() {
        let store = MemoryLinkCredentialsStore()
        XCTAssertNil(store.load())
        let credentials = LinkCredentials(
            deviceId: "device", hostId: "host", hostName: "Studio Desk", role: "controller",
            signingKeyBase64: Data(repeating: 1, count: 32).base64EncodedString()
        )
        store.save(credentials)
        XCTAssertEqual(store.load(), credentials)
        store.clear()
        XCTAssertNil(store.load())
    }
}
