// Generated by @deepseek-ai/dsh-link-contracts — regenerate with pnpm run gen-link-contracts; do not edit.

public enum LinkDeviceRole: String, Codable {
    case observer = "observer"
    case controller = "controller"
    case administrator = "administrator"
}
public enum LinkError: String, Codable {
    case linkUnavailable = "link-unavailable"
    case linkDisabled = "link-disabled"
    case badRequest = "bad-request"
}
public enum LinkJsonValue: Codable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case null
    case array([LinkJsonValue])
    case object([String: LinkJsonValue])

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() { self = .null; return }
        if let value = try? container.decode(Bool.self) { self = .bool(value); return }
        if let value = try? container.decode(Double.self) { self = .number(value); return }
        if let value = try? container.decode(String.self) { self = .string(value); return }
        if let value = try? container.decode([LinkJsonValue].self) { self = .array(value); return }
        if let value = try? container.decode([String: LinkJsonValue].self) { self = .object(value); return }
        throw DecodingError.dataCorruptedError(in: container, debugDescription: "unsupported JSON value")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .bool(let value): try container.encode(value)
        case .null: try container.encodeNil()
        case .array(let values): try container.encode(values)
        case .object(let entries): try container.encode(entries)
        }
    }
}
public struct LinkPairRequest: Codable {
    public let code: String
    public let deviceName: String
    public let devicePublicKey: String
}
public struct LinkRpcPayload: Codable {
    public let args: [String: LinkJsonValue]
}
public struct LinkRpcRequestEnvelope: Codable {
    public let type: String // constant "client-request"
    public let rpcId: String
    public let method: String
    public let payload: LinkRpcPayload
}
public struct LinkRpcError: Codable {
    public let code: String
    public let message: String
    public let details: [String: LinkJsonValue]
}
public struct LinkRpcResult: Codable {
    public let ok: Bool
    public let value: LinkJsonValue?
    public let error: LinkRpcError?
}
public struct LinkRpcResponseEnvelope: Codable {
    public let type: String // constant "server-response"
    public let rpcId: String
    public let result: LinkRpcResult
}
public struct LinkStreamRequest: Codable {
    public let args: [String: LinkJsonValue]
}
public enum LinkStreamFrameKind: String, Codable {
    case v = "v"
    case e = "e"
}
public struct LinkStreamFrame: Codable {
    public let k: LinkStreamFrameKind
    public let v: LinkJsonValue?
    public let c: String?
    public let m: String?
    public let d: [String: LinkJsonValue]?
}
public enum LinkRemoteEventFrameKind: String, Codable {
    case ready = "ready"
    case emit = "emit"
    case waterfall = "waterfall"
    case cancel = "cancel"
}
public enum LinkRemoteEventOutcomeKind: String, Codable {
    case next = "next"
    case result = "result"
    case rejected = "rejected"
}
public struct LinkRemoteEventHostInfo: Codable {
    public let home: String
}
public struct LinkRemoteEventReadyFrame: Codable {
    public let type: String // constant "ready"
    public let clientId: String
    public let host: LinkRemoteEventHostInfo
}
public struct LinkRemoteEventEmitFrame: Codable {
    public let type: String // constant "emit"
    public let event: String
    public let args: [LinkJsonValue]
}
public struct LinkRemoteEventWaterfallFrame: Codable {
    public let type: String // constant "waterfall"
    public let event: String
    public let eventId: String
    public let agentId: String
    public let request: [String: LinkJsonValue]
}
public struct LinkRemoteEventCancelFrame: Codable {
    public let type: String // constant "cancel"
    public let eventId: String
}
public struct LinkRemoteEventRejection: Codable {
    public let name: String
    public let message: String
    public let code: String?
    public let details: LinkJsonValue?
}
public struct LinkRemoteEventOutcome: Codable {
    public let kind: LinkRemoteEventOutcomeKind
    public let value: LinkJsonValue?
    public let error: LinkRemoteEventRejection?
}
public struct LinkRemoteEventResult: Codable {
    public let clientId: String
    public let eventId: String
    public let outcome: LinkRemoteEventOutcome
}
public struct LinkSessionEventRecord: Codable {
    public let type: String
    public let seq: Double
    public let time: Double
    public let data: LinkJsonValue
    public let sourceEventSeqs: [Double]?
    public let surfaceOp: LinkJsonValue?
}
public struct LinkSessionSnapshotFrame: Codable {
    public let type: String // constant "snapshot"
    public let header: [String: LinkJsonValue]
    public let cursor: Double
    public let records: [LinkJsonValue]
    public let hasMore: Bool
    public let projections: [String: LinkJsonValue]
}
public struct LinkPairingPayload: Codable {
    public let v: Double // constant 1
    public let kind: String // constant "dsh-link-pairing"
    public let hostId: String
    public let hostName: String
    public let endpoint: String
    public let spkiFingerprint: String
    public let code: String
    public let expiresAt: Double
}
public struct LinkPairResponse: Codable {
    public let deviceId: String
    public let hostId: String
    public let hostName: String
    public let role: LinkDeviceRole
    public let linkProtocolVersion: Double
}
public struct LinkSessionCapabilities: Codable {
    public let list: Bool
    public let history: Bool
    public let follow: Bool
    public let prompt: Bool
    public let cancel: Bool
}
public struct LinkWorkspaceCapabilities: Codable {
    public let follow: Bool
}
public struct LinkInteractionCapabilities: Codable {
    public let approval: Bool
    public let question: Bool
}
public struct LinkCapabilities: Codable {
    public let session: LinkSessionCapabilities
    public let workspace: LinkWorkspaceCapabilities
    public let interaction: LinkInteractionCapabilities
}
public struct LinkHostDescription: Codable {
    public let linkProtocolVersion: Double
    public let contractVersion: Double
    public let hostVersion: String
    public let hostId: String
    public let hostName: String
    public let runtimeClass: String
    public let sessionFormatVersion: Double
    public let allowRemoteApproval: Bool
    public let capabilities: LinkCapabilities
}
public struct LinkCarrierStatus: Codable {
    public let listening: Bool
    public let endpoint: String?
    public let spkiFingerprint: String?
    public let bindError: String?
}
public struct LinkDeviceRecord: Codable {
    public let deviceId: String
    public let name: String
    public let role: LinkDeviceRole
    public let createdAt: Double
    public let lastSeenAt: Double?
    public let revokedAt: Double?
}
public struct LinkAdminStatus: Codable {
    public let listening: Bool
    public let endpoint: String?
    public let spkiFingerprint: String?
    public let bindError: String?
    public let hostName: String
    public let allowRemoteApproval: Bool
    public let deviceCount: Double
}
public enum LinkSessionEventKind: String, Codable {
    case turnStart = "turn/start"
    case turnEnd = "turn/end"
    case stepStart = "step/start"
    case stepEnd = "step/end"
    case userMessage = "user/message"
    case assistantChunk = "assistant/chunk"
    case assistantMessage = "assistant/message"
    case toolCall = "tool/call"
    case toolResult = "tool/result"
    case artifactCreated = "artifact/created"
    case artifactStatus = "artifact/status"
    case planMode = "plan/mode"
    case todoWrite = "todo/write"
    case goalChange = "goal/change"
    case sessionEndSeed = "session/end-seed"
}
public enum LinkChunkRowKind: String, Codable {
    case chunkrowTextChunks = "chunkrow/text-chunks"
    case chunkrowReasoningChunks = "chunkrow/reasoning-chunks"
    case chunkrowToolCallChunks = "chunkrow/tool-call-chunks"
}
public enum LinkArtifactStatus: String, Codable {
    case pending = "pending"
    case ready = "ready"
    case failed = "failed"
}
public enum LinkArtifactFormat: String, Codable {
    case text = "text"
    case bytes = "bytes"
}
public enum LinkTodoStatus: String, Codable {
    case pending = "pending"
    case in_progress = "in_progress"
    case completed = "completed"
}
public enum LinkTurnEndReasonKind: String, Codable {
    case completed = "completed"
    case aborted = "aborted"
    case blocked = "blocked"
    case error = "error"
    case maxTokens = "max-tokens"
    case interrupted = "interrupted"
}
public enum LinkGoalOperation: String, Codable {
    case create = "create"
    case edit = "edit"
    case pause = "pause"
    case resume = "resume"
    case complete = "complete"
    case block = "block"
    case clear = "clear"
}
public enum LinkGoalPhase: String, Codable {
    case active = "active"
    case paused = "paused"
    case blocked = "blocked"
    case complete = "complete"
}
public struct LinkTodoItem: Codable {
    public let content: String
    public let status: LinkTodoStatus
}
public struct LinkTodoWriteData: Codable {
    public let todos: [LinkTodoItem]
}
public struct LinkArtifactCreatedData: Codable {
    public let id: String
    public let kind: String
    public let title: String
    public let format: LinkArtifactFormat
}
public struct LinkArtifactStatusData: Codable {
    public let id: String
    public let status: LinkArtifactStatus
}
public struct LinkPlanModeData: Codable {
    public let active: Bool
}
public struct LinkGoalBlockReason: Codable {
    public let code: String
    public let message: String
}
public struct LinkGoalSnapshot: Codable {
    public let id: String
    public let revision: Double
    public let objective: String
    public let phase: LinkGoalPhase
    public let blockedReason: LinkGoalBlockReason?
    public let maxGoalRounds: Double
}
public struct LinkGoalChangeData: Codable {
    public let kind: String // constant "goal/change"
    public let version: Double // constant 1
    public let operation: LinkGoalOperation
    public let goal: LinkGoalSnapshot?
    public let roundsStarted: Double?
    public let createdAt: Double?
    public let updatedAt: Double?
    public let clearedAt: Double?
}
public struct LinkTurnStartData: Codable {
    public let turn: Double
}
public struct LinkTurnEndReason: Codable {
    public let kind: LinkTurnEndReasonKind
}
public struct LinkTurnEndData: Codable {
    public let turn: Double
    public let reason: LinkTurnEndReason
}
public struct LinkStepSpanData: Codable {
    public let turn: Double
    public let step: Double
}
public struct LinkMessageSource: Codable {
    public let kind: String
    public let plugin: String?
    public let provider: String?
    public let model: String?
    public let callId: String?
}
public struct LinkContentBlock: Codable {
    public let type: String
    public let text: String?
    public let toolCallId: String?
    public let isError: Bool?
    public let attachment: LinkImageAttachmentRef?
    public let content: [LinkContentBlock]?
}
public struct LinkUserMessageData: Codable {
    public let id: String
    public let role: String // constant "user"
    public let content: [LinkContentBlock]
    public let source: LinkMessageSource
}
public struct LinkStreamChunk: Codable {
    public let type: String
    public let index: Double?
    public let text: String?
}
public struct LinkAssistantChunkData: Codable {
    public let turn: Double
    public let step: Double
    public let chunk: LinkStreamChunk
}
public struct LinkTokenUsage: Codable {
    public let inputTokens: Double
    public let outputTokens: Double
    public let totalTokens: Double?
}
public struct LinkAssistantMessage: Codable {
    public let id: String
    public let role: String // constant "assistant"
    public let content: [LinkContentBlock]
    public let source: LinkMessageSource
}
public struct LinkAssistantMessageData: Codable {
    public let turn: Double
    public let step: Double
    public let message: LinkAssistantMessage
    public let usage: LinkTokenUsage?
    public let interrupted: Bool?
}
public struct LinkToolCallData: Codable {
    public let turn: Double
    public let step: Double
    public let callId: String
    public let name: String
    public let arguments: String
}
public struct LinkToolError: Codable {
    public let name: String
    public let code: String
}
public struct LinkToolResultMessage: Codable {
    public let id: String
    public let role: String // constant "user"
    public let content: [LinkContentBlock]
    public let source: LinkMessageSource
}
public struct LinkToolResultData: Codable {
    public let turn: Double
    public let step: Double
    public let message: LinkToolResultMessage
    public let error: LinkToolError?
}
public struct LinkTextChunksData: Codable {
    public let turn: Double
    public let step: Double
    public let index: Double
    public let dt: [Double]
    public let texts: [String]
}
public struct LinkToolCallChunksData: Codable {
    public let turn: Double
    public let step: Double
    public let index: Double
    public let dt: [Double]
    public let id: String
    public let name: String?
    public let args: [String]
}
public enum LinkFileEntryType: String, Codable {
    case file = "file"
    case directory = "directory"
    case other = "other"
}
public struct LinkFileEntry: Codable {
    public let name: String
    public let type: LinkFileEntryType
    public let size: Double?
}
public struct LinkFileListValue: Codable {
    public let path: String
    public let entries: [LinkFileEntry]
}
public enum LinkSubagentActivity: String, Codable {
    case running = "running"
    case inactive = "inactive"
}
public enum LinkSubagentMode: String, Codable {
    case oneShot = "one-shot"
    case continuable = "continuable"
}
public enum LinkSubagentDiagnosticReason: String, Codable {
    case corrupt = "corrupt"
    case unsupported = "unsupported"
    case unavailable = "unavailable"
}
public struct LinkSubagentEntry: Codable {
    public let kind: String // constant "child"
    public let id: String
    public let activity: LinkSubagentActivity?
    public let hasChildren: Bool?
    public let mode: LinkSubagentMode?
    public let label: String?
    public let reason: LinkSubagentDiagnosticReason?
}
public struct LinkSubagentCatalog: Codable {
    public let entries: [LinkSubagentEntry]
    public let parentAvailable: Bool
}
public struct LinkFileReadValue: Codable {
    public let content: String
    public let truncated: Bool
    public let size: Double
    public let mediaType: String
}
public enum LinkImageMediaType: String, Codable {
    case imagePng = "image/png"
    case imageJpeg = "image/jpeg"
    case imageWebp = "image/webp"
    case imageGif = "image/gif"
}
public struct LinkImageDimensions: Codable {
    public let width: Double
    public let height: Double
}
public struct LinkImageAttachmentRef: Codable {
    public let attachmentId: String
    public let mediaType: LinkImageMediaType
    public let bytes: Double
    public let width: Double
    public let height: Double
    public let name: String?
    public let originalDimensions: LinkImageDimensions?
}
public struct LinkArtifactReadValue: Codable {
    public let id: String
    public let kind: String
    public let title: String
    public let format: LinkArtifactFormat
    public let data: String
    public let truncated: Bool
    public let size: Double
}
public enum LinkHandoffContextRole: String, Codable {
    case user = "user"
    case assistant = "assistant"
}
public struct LinkHandoffContextRow: Codable {
    public let role: LinkHandoffContextRole
    public let text: String
}
public struct LinkHandoffTodo: Codable {
    public let content: String
    public let status: String
}
public struct LinkHandoffArtifactRef: Codable {
    public let id: String
    public let kind: String
    public let title: String
    public let status: LinkArtifactStatus
}
public struct LinkHandoffProvenance: Codable {
    public let deviceId: String
    public let platform: String
    public let at: Double
}
public enum LinkHandoffRuntime: String, Codable {
    case lite = "lite"
}
public struct LinkHandoffSnapshot: Codable {
    public let sourceSessionId: String
    public let sourceRuntime: LinkHandoffRuntime
    public let requestedCapability: String
    public let recentContext: [LinkHandoffContextRow]
    public let planActive: Bool
    public let todo: [LinkHandoffTodo]
    public let artifactRefs: [LinkHandoffArtifactRef]
    public let modelPreference: String?
    public let provenance: LinkHandoffProvenance
}
public struct LinkHandoffValue: Codable {
    public let sessionId: String
}
public struct LinkAttachmentReadValue: Codable {
    public let attachment: LinkImageAttachmentRef
    public let data: String
}
public struct LinkPromptImagePart: Codable {
    public let type: String // constant "image"
    public let mediaType: LinkImageMediaType
    public let data: String
    public let name: String?
}
