// Generated by @deepseek-ai/dsh-link-contracts — regenerate with pnpm run gen-link-contracts; do not edit.

public enum LinkDeviceRole: String, Codable {
    case observer = "observer"
    case controller = "controller"
    case administrator = "administrator"
}
public enum LinkError: String, Codable {
    case linkUnavailable = "link-unavailable"
    case linkDisabled = "link-disabled"
    case badRequest = "bad-request"
}
public struct LinkPairingPayload: Codable {
    public let v: Double // constant 1
    public let kind: String // constant "dsh-link-pairing"
    public let hostId: String
    public let hostName: String
    public let endpoint: String
    public let spkiFingerprint: String
    public let code: String
    public let expiresAt: Double
}
public struct LinkPairResponse: Codable {
    public let deviceId: String
    public let hostId: String
    public let hostName: String
    public let role: LinkDeviceRole
    public let linkProtocolVersion: Double
}
public struct LinkSessionCapabilities: Codable {
    public let list: Bool
    public let history: Bool
    public let follow: Bool
    public let prompt: Bool
    public let cancel: Bool
}
public struct LinkWorkspaceCapabilities: Codable {
    public let follow: Bool
}
public struct LinkInteractionCapabilities: Codable {
    public let approval: Bool
    public let question: Bool
}
public struct LinkCapabilities: Codable {
    public let session: LinkSessionCapabilities
    public let workspace: LinkWorkspaceCapabilities
    public let interaction: LinkInteractionCapabilities
}
public struct LinkHostDescription: Codable {
    public let linkProtocolVersion: Double
    public let hostVersion: String
    public let hostId: String
    public let hostName: String
    public let runtimeClass: String
    public let sessionFormatVersion: Double
    public let allowRemoteApproval: Bool
    public let capabilities: LinkCapabilities
}
public struct LinkCarrierStatus: Codable {
    public let listening: Bool
    public let endpoint: String?
    public let spkiFingerprint: String?
    public let bindError: String?
}
public struct LinkDeviceRecord: Codable {
    public let deviceId: String
    public let name: String
    public let role: LinkDeviceRole
    public let createdAt: Double
    public let lastSeenAt: Double?
    public let revokedAt: Double?
}
public struct LinkAdminStatus: Codable {
    public let listening: Bool
    public let endpoint: String?
    public let spkiFingerprint: String?
    public let bindError: String?
    public let hostName: String
    public let allowRemoteApproval: Bool
    public let deviceCount: Double
}
