// swift-tools-version: 5.9
// The Apple Remote Companion's shared core: the link-client state machine
// (pair, describe, signed unary RPC, NDJSON Remote streams) over the wire
// models generated by @deepseek-ai/dsh-link-contracts. The apps (iOS,
// iPadOS, macOS companion) build on this library; nothing here imports UI
// frameworks.
import PackageDescription

let package = Package(
    name: "SharedAppleRemoteCore",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
    ],
    products: [
        .library(name: "SharedAppleRemoteCore", targets: ["SharedAppleRemoteCore"]),
    ],
    targets: [
        .target(
            name: "SharedAppleRemoteCore",
            path: "Sources/SharedAppleRemoteCore"
        ),
        .testTarget(
            name: "SharedAppleRemoteCoreTests",
            dependencies: ["SharedAppleRemoteCore"],
            path: "Tests/SharedAppleRemoteCoreTests",
            resources: [
                .copy("Fixtures"),
            ]
        ),
    ]
)
