// Generated by @deepseek-ai/dsh-link-contracts — regenerate with pnpm run gen-link-contracts; do not edit.

package ai.deepseek.dsh.link

enum class LinkDeviceRole(val wire: String) {
    OBSERVER("observer"),
    CONTROLLER("controller"),
    ADMINISTRATOR("administrator"),
}
enum class LinkError(val wire: String) {
    LINK_UNAVAILABLE("link-unavailable"),
    LINK_DISABLED("link-disabled"),
    BAD_REQUEST("bad-request"),
}
sealed class LinkJsonValue {
    data class StringValue(val value: String) : LinkJsonValue()
    data class NumberValue(val value: Double) : LinkJsonValue()
    data class BoolValue(val value: Boolean) : LinkJsonValue()
    data object NullValue : LinkJsonValue()
    data class ArrayValue(val items: List<LinkJsonValue>) : LinkJsonValue()
    data class ObjectValue(val entries: Map<String, LinkJsonValue>) : LinkJsonValue()
}
data class LinkPairRequest(
    val code: String,
    val deviceName: String,
    val devicePublicKey: String,
)
data class LinkRpcPayload(
    val args: Map<String, LinkJsonValue>,
)
data class LinkRpcRequestEnvelope(
    val type: String, // constant "client-request"
    val rpcId: String,
    val method: String,
    val payload: LinkRpcPayload,
)
data class LinkRpcError(
    val code: String,
    val message: String,
    val details: Map<String, LinkJsonValue>,
)
data class LinkRpcResult(
    val ok: Boolean,
    val value: LinkJsonValue? = null,
    val error: LinkRpcError? = null,
)
data class LinkRpcResponseEnvelope(
    val type: String, // constant "server-response"
    val rpcId: String,
    val result: LinkRpcResult,
)
data class LinkStreamRequest(
    val args: Map<String, LinkJsonValue>,
)
enum class LinkStreamFrameKind(val wire: String) {
    V("v"),
    E("e"),
}
data class LinkStreamFrame(
    val k: LinkStreamFrameKind,
    val v: LinkJsonValue? = null,
    val c: String? = null,
    val m: String? = null,
    val d: Map<String, LinkJsonValue>? = null,
)
enum class LinkRemoteEventFrameKind(val wire: String) {
    READY("ready"),
    EMIT("emit"),
    WATERFALL("waterfall"),
    CANCEL("cancel"),
}
enum class LinkRemoteEventOutcomeKind(val wire: String) {
    NEXT("next"),
    RESULT("result"),
    REJECTED("rejected"),
}
data class LinkRemoteEventHostInfo(
    val home: String,
)
data class LinkRemoteEventReadyFrame(
    val type: String, // constant "ready"
    val clientId: String,
    val host: LinkRemoteEventHostInfo,
)
data class LinkRemoteEventEmitFrame(
    val type: String, // constant "emit"
    val event: String,
    val args: List<LinkJsonValue>,
)
data class LinkRemoteEventWaterfallFrame(
    val type: String, // constant "waterfall"
    val event: String,
    val eventId: String,
    val agentId: String,
    val request: Map<String, LinkJsonValue>,
)
data class LinkRemoteEventCancelFrame(
    val type: String, // constant "cancel"
    val eventId: String,
)
data class LinkRemoteEventRejection(
    val name: String,
    val message: String,
    val code: String? = null,
    val details: LinkJsonValue? = null,
)
data class LinkRemoteEventOutcome(
    val kind: LinkRemoteEventOutcomeKind,
    val value: LinkJsonValue? = null,
    val error: LinkRemoteEventRejection? = null,
)
data class LinkRemoteEventResult(
    val clientId: String,
    val eventId: String,
    val outcome: LinkRemoteEventOutcome,
)
data class LinkSessionEventRecord(
    val type: String,
    val seq: Double,
    val time: Double,
    val data: LinkJsonValue,
    val sourceEventSeqs: List<Double>? = null,
    val surfaceOp: LinkJsonValue? = null,
)
data class LinkSessionSnapshotFrame(
    val type: String, // constant "snapshot"
    val header: Map<String, LinkJsonValue>,
    val cursor: Double,
    val records: List<LinkJsonValue>,
    val hasMore: Boolean,
    val projections: Map<String, LinkJsonValue>,
)
data class LinkPairingPayload(
    val v: Double, // constant 1
    val kind: String, // constant "dsh-link-pairing"
    val hostId: String,
    val hostName: String,
    val endpoint: String,
    val spkiFingerprint: String,
    val code: String,
    val expiresAt: Double,
)
data class LinkPairResponse(
    val deviceId: String,
    val hostId: String,
    val hostName: String,
    val role: LinkDeviceRole,
    val linkProtocolVersion: Double,
)
data class LinkSessionCapabilities(
    val list: Boolean,
    val history: Boolean,
    val follow: Boolean,
    val prompt: Boolean,
    val cancel: Boolean,
)
data class LinkWorkspaceCapabilities(
    val follow: Boolean,
)
data class LinkInteractionCapabilities(
    val approval: Boolean,
    val question: Boolean,
)
data class LinkCapabilities(
    val session: LinkSessionCapabilities,
    val workspace: LinkWorkspaceCapabilities,
    val interaction: LinkInteractionCapabilities,
)
data class LinkHostDescription(
    val linkProtocolVersion: Double,
    val contractVersion: Double,
    val hostVersion: String,
    val hostId: String,
    val hostName: String,
    val runtimeClass: String,
    val sessionFormatVersion: Double,
    val allowRemoteApproval: Boolean,
    val capabilities: LinkCapabilities,
)
data class LinkCarrierStatus(
    val listening: Boolean,
    val endpoint: String? = null,
    val spkiFingerprint: String? = null,
    val bindError: String? = null,
)
data class LinkDeviceRecord(
    val deviceId: String,
    val name: String,
    val role: LinkDeviceRole,
    val createdAt: Double,
    val lastSeenAt: Double? = null,
    val revokedAt: Double? = null,
)
data class LinkAdminStatus(
    val listening: Boolean,
    val endpoint: String? = null,
    val spkiFingerprint: String? = null,
    val bindError: String? = null,
    val hostName: String,
    val allowRemoteApproval: Boolean,
    val deviceCount: Double,
)
enum class LinkSessionEventKind(val wire: String) {
    TURN_START("turn/start"),
    TURN_END("turn/end"),
    STEP_START("step/start"),
    STEP_END("step/end"),
    USER_MESSAGE("user/message"),
    ASSISTANT_CHUNK("assistant/chunk"),
    ASSISTANT_MESSAGE("assistant/message"),
    TOOL_CALL("tool/call"),
    TOOL_RESULT("tool/result"),
    ARTIFACT_CREATED("artifact/created"),
    ARTIFACT_STATUS("artifact/status"),
    PLAN_MODE("plan/mode"),
    TODO_WRITE("todo/write"),
    GOAL_CHANGE("goal/change"),
    SESSION_END_SEED("session/end-seed"),
}
enum class LinkChunkRowKind(val wire: String) {
    CHUNKROW_TEXT_CHUNKS("chunkrow/text-chunks"),
    CHUNKROW_REASONING_CHUNKS("chunkrow/reasoning-chunks"),
    CHUNKROW_TOOL_CALL_CHUNKS("chunkrow/tool-call-chunks"),
}
enum class LinkArtifactStatus(val wire: String) {
    PENDING("pending"),
    READY("ready"),
    FAILED("failed"),
}
enum class LinkArtifactFormat(val wire: String) {
    TEXT("text"),
    BYTES("bytes"),
}
enum class LinkTodoStatus(val wire: String) {
    PENDING("pending"),
    IN_PROGRESS("in_progress"),
    COMPLETED("completed"),
}
enum class LinkTurnEndReasonKind(val wire: String) {
    COMPLETED("completed"),
    ABORTED("aborted"),
    BLOCKED("blocked"),
    ERROR("error"),
    MAX_TOKENS("max-tokens"),
    INTERRUPTED("interrupted"),
}
enum class LinkGoalOperation(val wire: String) {
    CREATE("create"),
    EDIT("edit"),
    PAUSE("pause"),
    RESUME("resume"),
    COMPLETE("complete"),
    BLOCK("block"),
    CLEAR("clear"),
}
enum class LinkGoalPhase(val wire: String) {
    ACTIVE("active"),
    PAUSED("paused"),
    BLOCKED("blocked"),
    COMPLETE("complete"),
}
data class LinkTodoItem(
    val content: String,
    val status: LinkTodoStatus,
)
data class LinkTodoWriteData(
    val todos: List<LinkTodoItem>,
)
data class LinkArtifactCreatedData(
    val id: String,
    val kind: String,
    val title: String,
    val format: LinkArtifactFormat,
)
data class LinkArtifactStatusData(
    val id: String,
    val status: LinkArtifactStatus,
)
data class LinkPlanModeData(
    val active: Boolean,
)
data class LinkGoalBlockReason(
    val code: String,
    val message: String,
)
data class LinkGoalSnapshot(
    val id: String,
    val revision: Double,
    val objective: String,
    val phase: LinkGoalPhase,
    val blockedReason: LinkGoalBlockReason? = null,
    val maxGoalRounds: Double,
)
data class LinkGoalChangeData(
    val kind: String, // constant "goal/change"
    val version: Double, // constant 1
    val operation: LinkGoalOperation,
    val goal: LinkGoalSnapshot? = null,
    val roundsStarted: Double? = null,
    val createdAt: Double? = null,
    val updatedAt: Double? = null,
    val clearedAt: Double? = null,
)
data class LinkTurnStartData(
    val turn: Double,
)
data class LinkTurnEndReason(
    val kind: LinkTurnEndReasonKind,
)
data class LinkTurnEndData(
    val turn: Double,
    val reason: LinkTurnEndReason,
)
data class LinkStepSpanData(
    val turn: Double,
    val step: Double,
)
data class LinkMessageSource(
    val kind: String,
    val plugin: String? = null,
    val provider: String? = null,
    val model: String? = null,
    val callId: String? = null,
)
data class LinkContentBlock(
    val type: String,
    val text: String? = null,
    val toolCallId: String? = null,
    val isError: Boolean? = null,
    val attachment: LinkImageAttachmentRef? = null,
    val content: List<LinkContentBlock>? = null,
)
data class LinkUserMessageData(
    val id: String,
    val role: String, // constant "user"
    val content: List<LinkContentBlock>,
    val source: LinkMessageSource,
)
data class LinkStreamChunk(
    val type: String,
    val index: Double? = null,
    val text: String? = null,
)
data class LinkAssistantChunkData(
    val turn: Double,
    val step: Double,
    val chunk: LinkStreamChunk,
)
data class LinkTokenUsage(
    val inputTokens: Double,
    val outputTokens: Double,
    val totalTokens: Double? = null,
)
data class LinkAssistantMessage(
    val id: String,
    val role: String, // constant "assistant"
    val content: List<LinkContentBlock>,
    val source: LinkMessageSource,
)
data class LinkAssistantMessageData(
    val turn: Double,
    val step: Double,
    val message: LinkAssistantMessage,
    val usage: LinkTokenUsage? = null,
    val interrupted: Boolean? = null,
)
data class LinkToolCallData(
    val turn: Double,
    val step: Double,
    val callId: String,
    val name: String,
    val arguments: String,
)
data class LinkToolError(
    val name: String,
    val code: String,
)
data class LinkToolResultMessage(
    val id: String,
    val role: String, // constant "user"
    val content: List<LinkContentBlock>,
    val source: LinkMessageSource,
)
data class LinkToolResultData(
    val turn: Double,
    val step: Double,
    val message: LinkToolResultMessage,
    val error: LinkToolError? = null,
)
data class LinkTextChunksData(
    val turn: Double,
    val step: Double,
    val index: Double,
    val dt: List<Double>,
    val texts: List<String>,
)
data class LinkToolCallChunksData(
    val turn: Double,
    val step: Double,
    val index: Double,
    val dt: List<Double>,
    val id: String,
    val name: String? = null,
    val args: List<String>,
)
enum class LinkFileEntryType(val wire: String) {
    FILE("file"),
    DIRECTORY("directory"),
    OTHER("other"),
}
data class LinkFileEntry(
    val name: String,
    val type: LinkFileEntryType,
    val size: Double? = null,
)
data class LinkFileListValue(
    val path: String,
    val entries: List<LinkFileEntry>,
)
enum class LinkSubagentActivity(val wire: String) {
    RUNNING("running"),
    INACTIVE("inactive"),
}
enum class LinkSubagentMode(val wire: String) {
    ONE_SHOT("one-shot"),
    CONTINUABLE("continuable"),
}
enum class LinkSubagentDiagnosticReason(val wire: String) {
    CORRUPT("corrupt"),
    UNSUPPORTED("unsupported"),
    UNAVAILABLE("unavailable"),
}
data class LinkSubagentEntry(
    val kind: String, // constant "child"
    val id: String,
    val activity: LinkSubagentActivity? = null,
    val hasChildren: Boolean? = null,
    val mode: LinkSubagentMode? = null,
    val label: String? = null,
    val reason: LinkSubagentDiagnosticReason? = null,
)
data class LinkSubagentCatalog(
    val entries: List<LinkSubagentEntry>,
    val parentAvailable: Boolean,
)
data class LinkFileReadValue(
    val content: String,
    val truncated: Boolean,
    val size: Double,
    val mediaType: String,
)
enum class LinkImageMediaType(val wire: String) {
    IMAGE_PNG("image/png"),
    IMAGE_JPEG("image/jpeg"),
    IMAGE_WEBP("image/webp"),
    IMAGE_GIF("image/gif"),
}
data class LinkImageDimensions(
    val width: Double,
    val height: Double,
)
data class LinkImageAttachmentRef(
    val attachmentId: String,
    val mediaType: LinkImageMediaType,
    val bytes: Double,
    val width: Double,
    val height: Double,
    val name: String? = null,
    val originalDimensions: LinkImageDimensions? = null,
)
data class LinkArtifactReadValue(
    val id: String,
    val kind: String,
    val title: String,
    val format: LinkArtifactFormat,
    val data: String,
    val truncated: Boolean,
    val size: Double,
)
enum class LinkHandoffContextRole(val wire: String) {
    USER("user"),
    ASSISTANT("assistant"),
}
data class LinkHandoffContextRow(
    val role: LinkHandoffContextRole,
    val text: String,
)
data class LinkHandoffTodo(
    val content: String,
    val status: String,
)
data class LinkHandoffArtifactRef(
    val id: String,
    val kind: String,
    val title: String,
    val status: LinkArtifactStatus,
)
data class LinkHandoffProvenance(
    val deviceId: String,
    val platform: String,
    val at: Double,
)
enum class LinkHandoffRuntime(val wire: String) {
    LITE("lite"),
}
data class LinkHandoffSnapshot(
    val sourceSessionId: String,
    val sourceRuntime: LinkHandoffRuntime,
    val requestedCapability: String,
    val recentContext: List<LinkHandoffContextRow>,
    val planActive: Boolean,
    val todo: List<LinkHandoffTodo>,
    val artifactRefs: List<LinkHandoffArtifactRef>,
    val modelPreference: String? = null,
    val provenance: LinkHandoffProvenance,
)
data class LinkHandoffValue(
    val sessionId: String,
)
data class LinkAttachmentReadValue(
    val attachment: LinkImageAttachmentRef,
    val data: String,
)
data class LinkPromptImagePart(
    val type: String, // constant "image"
    val mediaType: LinkImageMediaType,
    val data: String,
    val name: String? = null,
)
